module.exports = [
	'',
	'`',
	'´',
	'_',
	'.',
	'-',
	'+',
	'˙',
	'"',
	'<',
	'>',
	';',
	'&',
	'@',
	'--',
	'\\',
	'//',
	'\n',
	'\r',
	'\'',
	'://',
	'\n\r',
	'%00',
	'\\x00',
	'\u0000',
	'\\0',
	'null',
	'undefined',
	new Buffer(0x32).toString('utf8'),
	String.fromCharCode(0),
	String.fromCharCode(1),
	String.fromCharCode(Math.pow(2, 8)),
	String.fromCharCode(Math.pow(2, 8) + 1),
	String.fromCharCode(Math.pow(2, 8) - 1),
	String.fromCharCode(Math.pow(2, 16)),
	String.fromCharCode(Math.pow(2, 16) + 1),
	String.fromCharCode(Math.pow(2, 16) - 1),
	String.fromCharCode(Math.pow(2, 32)),
	String.fromCharCode(Math.pow(2, 32) + 1),
	String.fromCharCode(Math.pow(2, 32) - 1)
];
